# Generated by Django 3.1.1 on 2021-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='number',
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_day',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='st_phone',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='step',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
