# Generated by Django 3.1.1 on 2021-03-30 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20210330_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('st_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.student')),
            ],
        ),
    ]
