# Generated by Django 3.1.1 on 2021-04-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_auto_20210330_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_date',
            field=models.TextField(default=''),
        ),
    ]
